vcenter_host: "vc.lab.local"
vcenter_user: "{{ vault_vcenter_user }}"
vcenter_pass: "{{ vault_vcenter_pass }}"

snmp_devices:
  - name: nas
    ip: 192.168.1.79
    community: "{{ vault_snmp_community }}"
    profile: qnap
    if_allow_regex: "^(eth0|bond0|vlan\\d+)$"

  - name: aquarius
    ip: 192.168.1.182
    community: "{{ vault_snmp_community }}"
    profile: qnap
    if_allow_regex: "^(eth0|bond0|vlan\\d+)$"

  - name: usg
    ip: 192.168.1.1
    community: "{{ vault_snmp_community }}"
    profile: ubiquiti

  - name: usw-lite
    ip: 192.168.1.229
    community: "{{ vault_snmp_community }}"
    profile: ubiquiti-switch

  - name: antares1
    ip: 192.168.1.170
    community: "{{ vault_snmp_community }}"
    profile: supermicro

  - name: antares2
    ip: 192.168.1.171
    community: "{{ vault_snmp_community }}"
    profile: supermicro

  - name: lyra
    ip: 192.168.1.253
    community: "{{ vault_snmp_community }}"
    profile: opnsense

collector_enable_ufw: false
collector_allow_lan_cidr: "192.168.1.0/24"
